var friendAge = [15, 17, 14, 16];
var aupu = friendAge[0];
friendAge[1] = 35;
var position = friendAge.indexOf(100);
//console.log(aupu);
//console.log(friendAge[3]);
//console.log(friendAge);
//console.log(position);
//console.log(friendAge.length);
console.log(friendAge);
friendAge.push(15);
friendAge.push(19);
friendAge.push(45);
friendAge.unshift(100);
//console.log(friendAge.length);
console.log(friendAge);
friendAge.pop();
friendAge.pop();
friendAge.shift();
console.log(friendAge);
